// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFDUtn-oZ_fCiWKwuqBtvhFkM7hzuqTk',
    appId: '1:367639018823:web:3c2982fc052dde09712062',
    messagingSenderId: '367639018823',
    projectId: 'duedates-df7ed',
    authDomain: 'duedates-df7ed.firebaseapp.com',
    storageBucket: 'duedates-df7ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEP9h-KhS_bx2G9z2aMEqsQtdduWolSQ0',
    appId: '1:367639018823:android:2f1e7c71c0d38542712062',
    messagingSenderId: '367639018823',
    projectId: 'duedates-df7ed',
    storageBucket: 'duedates-df7ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMfEx17YbDXD4O1Dqetu5zsrnQvejUCzM',
    appId: '1:367639018823:ios:bb264b9231228966712062',
    messagingSenderId: '367639018823',
    projectId: 'duedates-df7ed',
    storageBucket: 'duedates-df7ed.appspot.com',
    iosBundleId: 'com.srijon.dueDates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMfEx17YbDXD4O1Dqetu5zsrnQvejUCzM',
    appId: '1:367639018823:ios:61838286fb952f87712062',
    messagingSenderId: '367639018823',
    projectId: 'duedates-df7ed',
    storageBucket: 'duedates-df7ed.appspot.com',
    iosBundleId: 'com.srijon.dueDates.RunnerTests',
  );
}
